<?php

namespace iut\TaskBundle\Entity;

use Doctrine\ORM\EntityRepository;
use HappyR\Google\ApiBundle\Services\GoogleClient;

/**
 * ListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListTaskRepository extends EntityRepository
{
	private $client;

	public function setClient(\Google_Client $client)
	{
		$this->client = $client;
		$this->client->setScopes([\Google_Service_Tasks::TASKS]);
	}

	public function findAll()
	{
		$taskList = array();
		$service = new \Google_Service_Tasks($this->client);
		$googleTaskLists = $service->tasklists->listTasklists();

		foreach ($googleTaskLists as $googleTaskItem) {
		  	array_push($taskList, $this->convertGoogleTask($googleTaskItem));
		}
		return $taskList;
	}

	public function find($id)
	{
		$list = array();
		$service = new \Google_Service_Tasks($this->client);
		$googleTaskList = $service->tasks->listTasks($id);
		$taskList = $service->tasklists->get($id);
		$taskList = $this->convertGoogleTaskItem($googleTaskList,$taskList);
		return $taskList;
	}

	private function convertGoogleTask($taskItem)
	{
		$task = new ListTask();
	  	$task->setId($taskItem->getId());
	  	$task->setName($taskItem->getTitle());
	  	return $task;
	}

	private function convertGoogleTaskItem($googleTaskList, $taskList)
	{
		$task = new ListTask();
	  	$task->setId($taskList->getId());
	  	$task->setName($taskList->getTitle());
	  	$taskItems = $googleTaskList->getItems();
	  	foreach ($taskItems as $item) {
	  		$itemTask = new Task();
	  		$itemTask->setId($item->getId());
	  		$itemTask->setName($item->getTitle());
	  		$itemTask->setDescription($item->getNotes());
	  		$itemTask->setCheck($item->getStatus());
	  		$itemTask->setListTask($task);
	  		$task->addTask($itemTask);
	  	}
	  	return $task;
	}
}
