<?php

namespace iut\TaskBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
	private $client;

	public function setClient(\Google_Client $client)
	{
		$this->client = $client;
		$this->client->setScopes([\Google_Service_Tasks::TASKS]);
	}

	public function findTask($idTask, $idList)
	{
		$service = new \Google_Service_Tasks($this->client);
		return $service->tasks->get($idList, $idTask);
	}
	
	public function updateTask($idTask, $idList, $task)
	{
		$service = new \Google_Service_Tasks($this->client);
		$service->tasks->update($idList, $idTask, $task);
	}

	public function insertTask($task, $idList)
	{
		$service = new \Google_Service_Tasks($this->client);
		$tt = $this->convertGoogleTask($task);
		$service->tasks->insert($idList, $tt);
	}

	public function removeTask($idTask, $idList)
	{
		$service = new \Google_Service_Tasks($this->client);
		$service->tasks->delete($idList, $idTask);
	}

	public function convertGoogleTask($task)
	{
		$googleTask = new \Google_Service_Tasks_Task();
		$googleTask->setId($task->getId());
		$googleTask->setTitle($task->getName());
		$googleTask->setNotes($task->getDescription());
		$googleTask->setCompleted($task->getCheck());
		return $googleTask;
	}
}
